const { _electron: electron } = require('playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname,'..');
const runId = new Date().toISOString().replace(/[:.]/g,'-');
const evidence = path.join(root,'work',`e2e-${runId}`);
const dataDir = path.join(evidence,'data');
const results = [];
let desktop, page;
const errors = [];
const env = {...process.env,FLOWLINE_TEST:'1',FLOWLINE_DATA_DIR:dataDir}; delete env.ELECTRON_RUN_AS_NODE;
const screenshot = async name => { await page.waitForTimeout(550); await page.locator('#toast').waitFor({state:'hidden',timeout:8000}); return page.screenshot({path:path.join(evidence,`${name}.png`)}); };
const check = (name, detail = '') => { results.push({name,status:'passed',detail}); console.log('PASS',name,detail); };
async function launch() {
  desktop = await electron.launch({...(process.env.FLOWLINE_PACKAGED === '1' ? {executablePath:path.join(root,'release-public/Flowline-win32-x64/Flowline.exe'),args:[]} : {args:[root]}),env,timeout:30000});
  page = await desktop.firstWindow();
  page.on('pageerror',error => errors.push(error.message));
  page.on('console',msg => { if(msg.type() === 'error') errors.push(msg.text()); });
  await page.getByRole('button',{name:'打开主页',exact:true}).click(); await page.waitForSelector('#stage h2');
}
async function state() { const result = await page.evaluate(() => window.flowline.load()); assert.equal(result.ok,true); return result.value.state; }
async function waitState(predicate) { for(let i=0;i<60;i++){const s=await state();if(predicate(s)) return s;await page.waitForTimeout(50);}throw new Error('State did not settle');}
async function closeModal() { await page.locator('dialog [data-close]').first().click(); await page.waitForFunction(() => !document.querySelector('dialog').open); }
async function main() {
  await fs.mkdir(evidence,{recursive:true}); await launch();
  await screenshot('01-empty');
  assert.equal((await state()).tasks.length,0); check('First launch is empty and honest');
  await page.getByRole('button',{name:'先看看示例 →'}).click();
  await page.waitForSelector('.timeline-card.active'); assert.equal(await page.locator('.timeline-card').count(),3);
  await screenshot('02-timelines-v1'); check('Three timeline cards with depth previews');
  const initialTitle = await page.locator('.active h2').textContent();
  await page.getByRole('button',{name:'下一条时间线',exact:true}).click(); assert.notEqual(await page.locator('.active h2').textContent(),initialTitle);
  await page.keyboard.press('ArrowLeft'); assert.equal(await page.locator('.active h2').textContent(),initialTitle);
  await page.locator('#stage').dispatchEvent('wheel',{deltaX:130,deltaY:0}); assert.notEqual(await page.locator('.active h2').textContent(),initialTitle); check('Button, keyboard and horizontal wheel navigation');
  await page.getByRole('button',{name:'设置',exact:true}).click();
  await page.getByRole('button',{name:'左侧',exact:true}).click();
  await waitState(s=>s.settings.side==='left');
  const bounds = await desktop.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].getBounds());
  const workArea = await desktop.evaluate(({screen}) => screen.getPrimaryDisplay().workArea);
  assert.equal(bounds.x,workArea.x); check('Left docking moves real native window');
  await page.getByRole('button',{name:'右侧',exact:true}).click();
  await waitState(s=>s.settings.side==='right'); await page.locator('#motion-setting').check(); await waitState(s=>s.settings.reducedMotion);
  await screenshot('03-settings'); await closeModal();
  await page.getByRole('button',{name:'收起到屏幕边缘',exact:true}).click();
  await page.waitForFunction(() => document.body.dataset.collapsed === 'true');
  const ignores = await desktop.evaluate(({BrowserWindow}) => { const w=BrowserWindow.getAllWindows()[0]; return w.isVisible(); });
  assert.equal(ignores,true); await screenshot('04-edge');
  // Native polling: supply cursor position through Electron screen API for deterministic activation.
  await desktop.evaluate(({screen,BrowserWindow}) => { globalThis.originalCursor = screen.getCursorScreenPoint; const b=BrowserWindow.getAllWindows()[0].getBounds(); screen.getCursorScreenPoint = () => ({x:b.x+b.width-3,y:b.y+Math.floor(b.height/2)}); });
  await page.waitForFunction(() => document.body.dataset.collapsed === 'false');
  await desktop.evaluate(({screen}) => { screen.getCursorScreenPoint = globalThis.originalCursor; });
  check('Collapsed strip and native cursor activation'); await page.getByRole('button',{name:'打开主页',exact:true}).click();
  await page.locator('#new-task').click();
  await page.getByRole('textbox',{name:'任务名称',exact:true}).fill('验证截图与任务进度');
  await page.getByRole('textbox',{name:'节点内容',exact:true}).fill('开始验证');
  await page.getByRole('textbox',{name:'下一步',exact:true}).fill('拖入截图并检查保存');
  await page.getByRole('button',{name:'创建时间线',exact:true}).click();
  await page.waitForFunction(() => !document.querySelector('dialog').open);
  assert.equal((await state()).tasks[0].title,'验证截图与任务进度'); check('Create task through editor');
  const png = await page.screenshot();
  const pngPath = path.join(evidence,'fixture.png'); await fs.writeFile(pngPath,png);
  await desktop.evaluate(({clipboard,ClipboardItem},base64) => {globalThis.originalClipboardRead=clipboard.read;clipboard.read=async()=>[new ClipboardItem({'image/png':new Blob([Buffer.from(base64,'base64')],{type:'image/png'})})];},png.toString('base64'));
  await page.locator('#record').click(); await page.getByRole('button',{name:'粘贴截图',exact:true}).click(); await page.waitForSelector('.attachment-preview img'); await closeModal(); await desktop.evaluate(({clipboard})=>{clipboard.read=globalThis.originalClipboardRead;}); check('Clipboard image API fixture attaches without calling AI');
  const dt = await page.evaluateHandle(base64 => { const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0)); const dt=new DataTransfer(); dt.items.add(new File([bytes],'progress.png',{type:'image/png'})); return dt; },png.toString('base64'));
  await page.locator('#shell').dispatchEvent('dragenter',{dataTransfer:dt});
  await page.waitForSelector('#drop-overlay:not([hidden])');
  await page.locator('[data-drop="append"]').dispatchEvent('dragover',{dataTransfer:dt});
  await screenshot('05-drop-zones');
  await page.locator('[data-drop="append"]').dispatchEvent('drop',{dataTransfer:dt});
  await page.waitForSelector('#editor'); await page.waitForSelector('.attachment-preview img');
  await page.getByRole('textbox',{name:'节点内容',exact:true}).fill('截图关联完成');
  await page.getByRole('textbox',{name:'补充说明',exact:true}).fill('界面截图已与这个节点关联，不调用 AI。');
  await screenshot('06-capture-editor');
  await page.getByRole('button',{name:'保存这个节点',exact:true}).click();
  await page.waitForFunction(() => !document.querySelector('dialog').open);
  let s = await state(); const taskId=s.tasks[0].id, imageId=s.tasks[0].nodes.at(-1).image; assert.ok(imageId);
  assert.ok((await fs.stat(path.join(dataDir,'images',`${imageId}.png`))).size > 0); check('Drop into update zone persists screenshot and node');
  await page.getByRole('button',{name:'查看截图：截图关联完成'}).click(); await page.waitForSelector('.image-view');
  assert.ok(await page.locator('.image-view').evaluate(img => img.complete && img.naturalWidth > 0)); await closeModal(); check('Saved screenshot opens correctly');
  await page.getByRole('button',{name:'编辑当前任务'}).click();
  await page.locator('select[name="status"]').selectOption('done'); await page.getByRole('button',{name:'保存调整'}).click();
  await page.waitForFunction(() => !document.querySelector('dialog').open);
  assert.equal((await state()).tasks.find(t=>t.id===taskId).status,'done'); check('Completion moves task to completed view');
  await page.getByRole('button',{name:'撤销',exact:true}).click(); await waitState(s=>s.tasks.find(t=>t.id===taskId).status==='active'); check('Undo restores previous task state');
  await page.locator('[data-filter="active"]').click();
  if(await page.locator(`[data-select="${taskId}"]`).count()) await page.locator(`[data-select="${taskId}"]`).first().click();
  await page.getByRole('button',{name:'编辑当前任务'}).click(); await page.getByRole('button',{name:'归档这条时间线'}).click();
  await page.waitForFunction(() => !document.querySelector('dialog').open);
  assert.equal((await state()).tasks.find(t=>t.id===taskId).archived,true);
  await page.getByRole('button',{name:'设置',exact:true}).click(); await page.locator(`[data-restore="${taskId}"]`).click();
  await waitState(s=>s.tasks.find(t=>t.id===taskId).archived===false); await closeModal(); check('Archive and restore keep all records');
  const bad = await page.evaluate(() => window.flowline.importImage(new Uint8Array([1,2,3]))); assert.equal(bad.ok,false);
  const traversal = await page.evaluate(() => window.flowline.getImage('../../package')); assert.equal(traversal.ok,false);
  const ai = await page.evaluate(() => window.flowline.analyze({})); assert.equal(ai.value.status,'unconfigured');
  check('Invalid images, path traversal rejected; AI stays offline');
  const large = await page.evaluate(() => window.flowline.importImage(new Uint8Array(12*1024*1024+1))); assert.equal(large.ok,false); check('Oversized image is rejected');
  const beforeCreateDrop = (await state()).tasks.length;
  await page.locator('#shell').dispatchEvent('dragenter',{dataTransfer:dt}); await page.locator('[data-drop="create"]').dispatchEvent('drop',{dataTransfer:dt}); await page.waitForSelector('#editor'); await page.waitForSelector('.attachment-preview'); await page.getByRole('textbox',{name:'任务名称',exact:true}).fill('从截图开始的新任务'); await page.getByRole('textbox',{name:'节点内容',exact:true}).fill('保存参考截图'); await page.getByRole('button',{name:'创建时间线',exact:true}).click(); await page.waitForFunction(() => !document.querySelector('dialog').open); assert.equal((await state()).tasks.length,beforeCreateDrop+1); check('Upper drop zone creates a new task with screenshot');
  await page.getByRole('button',{name:'撤销',exact:true}).click(); await waitState(s=>s.tasks.length===beforeCreateDrop);
  await page.locator('#new-task').click(); await page.getByRole('textbox',{name:'任务名称',exact:true}).fill('<img src=x onerror=alert(1)> & 长标题'.repeat(2)); await page.getByRole('textbox',{name:'节点内容',exact:true}).fill('确认 HTML 被当作文字'); await page.getByRole('button',{name:'创建时间线',exact:true}).click(); await page.waitForFunction(() => !document.querySelector('dialog').open); assert.equal(await page.locator('.card-title-row h2 img').count(),0); assert.match(await page.locator('.active h2').textContent(),/<img/); check('User content is escaped, including long titles'); await page.getByRole('button',{name:'撤销',exact:true}).click(); await waitState(s=>s.tasks.length===beforeCreateDrop);
  const backupPath = path.join(evidence,'workspace.flowline');
  await desktop.evaluate(({dialog},filePath) => { dialog.showSaveDialog=async()=>({canceled:false,filePath}); },backupPath);
  const exported = await page.evaluate(() => window.flowline.exportBackup()); assert.equal(exported.ok,true);
  const bundle=JSON.parse(await fs.readFile(backupPath,'utf8')); assert.ok(bundle.images[imageId]);
  await desktop.evaluate(({dialog},filePath) => { dialog.showOpenDialog=async()=>({canceled:false,filePaths:[filePath]}); dialog.showMessageBox=async()=>({response:1}); },backupPath);
  const imported = await page.evaluate(() => window.flowline.importBackup()); assert.equal(imported.ok,true); assert.equal(imported.value.state.tasks.length,s.tasks.length);
  assert.notEqual(imported.value.state.tasks.find(t=>t.id===taskId).nodes.at(-1).image,imageId); check('Backup round-trip includes images and remaps IDs safely');
  await desktop.close(); await launch();
  assert.equal((await state()).tasks.find(t=>t.id===taskId).nodes.length,2); check('Full desktop restart retains task and screenshot');
  await desktop.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].setBounds({width:448,height:620}));
  await page.waitForTimeout(200); await screenshot('07-compact-620');
  const overflow = await page.evaluate(() => ({body:document.body.scrollHeight > innerHeight, footer:document.querySelector('.footer').getBoundingClientRect().bottom > innerHeight}));
  assert.equal(overflow.body,false); assert.equal(overflow.footer,false);
  const nodeVisible=await page.evaluate(()=>{const a=document.querySelector('.node.current .node-title').getBoundingClientRect(),b=document.querySelector('.timeline-scroll').getBoundingClientRect();return a.top>=b.top && a.bottom<=b.bottom;}); assert.equal(nodeVisible,true);
  await page.locator('#record').click(); const formBounds=await page.locator('.modal-actions').boundingBox(); assert.ok(formBounds.y+formBounds.height<=620); await closeModal(); check('Compact 620 px window preserves current title, footer and editor actions');
  await desktop.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].setBounds({width:448,height:800}));
  await page.waitForTimeout(200); await screenshot('08-final-workspace');
  const security = await desktop.evaluate(({BrowserWindow}) => { const p=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences(); return {node:p.nodeIntegration,isolation:p.contextIsolation,sandbox:p.sandbox}; });
  assert.deepEqual(security,{node:false,isolation:true,sandbox:true}); check('Renderer isolation and sandbox enabled');
  assert.equal(errors.length,0,errors.join('\n')); check('No renderer exceptions or console errors');
}
main().catch(error => { console.error(error); results.push({name:'Run failed',status:'failed',detail:error.stack}); process.exitCode=1; })
.finally(async () => { if (desktop) await desktop.close().catch(()=>{}); await fs.writeFile(path.join(evidence,'results.json'),JSON.stringify({runId,results,errors},null,2)); console.log('Evidence:',evidence); });
