const {_electron:electron}=require('playwright');const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'work','reel-'+Date.now()),results=[];let app;
const check=name=>{results.push({name,status:'passed'});console.log('PASS',name);};
(async()=>{
 await fs.mkdir(dir,{recursive:true});const env={...process.env,FLOWLINE_TEST:'1',FLOWLINE_DATA_DIR:path.join(dir,'data')};delete env.ELECTRON_RUN_AS_NODE;
 app=await electron.launch({...(process.env.FLOWLINE_PACKAGED==='1'?{executablePath:path.join(root,'release-public/Flowline-win32-x64/Flowline.exe'),args:[]}:{args:[root]}),env});const p=await app.firstWindow(),errors=[];p.on('pageerror',x=>errors.push(x.message));p.on('console',x=>{if(x.type()==='error')errors.push(x.text());});
 await p.waitForSelector('#widget-home');assert.equal((await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].getBounds())).width,280);check('Wider 280px screen-height widget');
 await p.getByRole('button',{name:'打开主页',exact:true}).click();await p.locator('#new-task').click();await p.locator('#oa-template').click();await p.getByRole('textbox',{name:'任务名称',exact:true}).fill('项目费用 · OA 审批');await p.locator('#workflow-current').selectOption('3');await p.getByRole('button',{name:'创建时间线',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('dialog').open);await p.getByRole('button',{name:'回到极简挂件'}).click();await p.waitForSelector('.reel-column.focused');
 assert.equal(await p.locator('.reel-column.focused .reel-step').count(),10);assert.match(await p.locator('.widget-caption').textContent(),/等待直属主管审批/);assert.equal(await p.locator('.reel-column.focused .complete').count(),3);check('OA template displays ten real named steps, current and future');
 await p.waitForTimeout(300);await p.screenshot({path:path.join(dir,'workflow.png')});
 await p.locator('.focused .step-advance').click();await p.waitForFunction(()=>document.querySelector('.widget-caption').textContent==='等待部门负责人审批');let s=(await p.evaluate(()=>window.flowline.load())).value.state;assert.equal(s.tasks[0].workflow.current,4);check('Complete-step action advances and persists');
 await p.keyboard.press('Control+z');await p.waitForFunction(()=>document.querySelector('.widget-caption').textContent==='等待直属主管审批');check('Undo restores process position');
 for(let i=0;i<3;i++){await p.getByRole('button',{name:'打开主页',exact:true}).click();await p.locator('#new-task').click();assert.equal(await p.locator('[name="workflowSteps"]').inputValue(),'');await p.getByRole('textbox',{name:'任务名称',exact:true}).fill(['合同会签','采购申请','客户交付'][i]);await p.getByRole('textbox',{name:'节点内容',exact:true}).fill('开始跟进');await p.locator('[name="workflowSteps"]').fill(Array.from({length:18},(_,j)=>`环节 ${j+1} · ${['确认材料','等待反馈','完成审核'][j%3]}`).join('\n'));await p.locator('#workflow-current').selectOption('8');await p.getByRole('button',{name:'创建时间线',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('dialog').open);await p.getByRole('button',{name:'回到极简挂件'}).click();}
 assert.equal(await p.locator('.focused .reel-step').count(),18);const scroll=await p.locator('.focused .reel-step-scroll').evaluate(el=>({height:el.clientHeight,total:el.scrollHeight}));assert.ok(scroll.total>scroll.height);check('All 18 steps are retained and vertically scrollable');
 const first=await p.locator('.widget-title').textContent();const box=await p.locator('.reel-viewport').boundingBox();await p.mouse.move(box.x+130,box.y+200);await p.mouse.down();await p.mouse.move(box.x+90,box.y+200,{steps:6});const mid=Number(await p.locator('.reel-viewport').getAttribute('data-position'));assert.ok(mid>0.1&&mid<.9);await p.screenshot({path:path.join(dir,'drag-midpoint.png')});await p.mouse.move(box.x+35,box.y+200,{steps:8});await p.mouse.up();await p.waitForTimeout(1100);assert.notEqual(await p.locator('.widget-title').textContent(),first);assert.equal(await p.locator('dialog').getAttribute('open'),null);check('Pointer drag has fractional in-between positions and no accidental edit');
 await p.locator('.reel-viewport').dispatchEvent('wheel',{deltaX:105,deltaY:0});const frames=[];for(let i=0;i<12;i++){await p.waitForTimeout(45);frames.push(Number(await p.locator('.reel-viewport').getAttribute('data-position')));}assert.ok(new Set(frames.map(x=>x.toFixed(2))).size>=4);await p.waitForTimeout(900);const settled=Number(await p.locator('.reel-viewport').getAttribute('data-position'));assert.ok(Math.abs(settled-Math.round(settled))<.01);check('Wheel moves through multiple frames and springs to a task');
 for(let i=0;i<4&&!(await p.locator('.widget-title').textContent()).includes('OA');i++){await p.getByRole('button',{name:'下一条时间线',exact:true}).click();await p.waitForTimeout(900);}await p.waitForTimeout(3500);assert.equal(await p.locator('#widget-toast').isVisible(),false);check('Old widget notice clears after switching views');await p.screenshot({path:path.join(dir,'wide-workflow.png')});
  await fs.mkdir(path.join(dir,'frames'),{recursive:true});await p.getByRole('button',{name:'下一条时间线',exact:true}).click();for(let i=0;i<16;i++){await p.screenshot({path:path.join(dir,'frames',String(i).padStart(2,'0')+'.png')});await p.waitForTimeout(30);}await p.waitForTimeout(300);
  await p.getByRole('button',{name:'打开主页',exact:true}).click();await p.getByRole('button',{name:'设置',exact:true}).click();await p.locator('#motion-setting').check();await p.waitForFunction(async()=>(await window.flowline.load()).value.state.settings.reducedMotion);await p.locator('dialog [data-close]').first().click();await p.getByRole('button',{name:'回到极简挂件'}).click();const title=await p.locator('.widget-title').textContent();await p.getByRole('button',{name:'下一条时间线',exact:true}).click();await p.waitForFunction(title=>document.querySelector('.widget-title').textContent!==title,title);check('Reduced motion remains functional');
 await fs.writeFile(path.join(dir,'motion-samples.json'),JSON.stringify(frames));assert.equal(errors.length,0,errors.join('\n'));check('No renderer errors');
})().catch(error=>{console.error(error);results.push({name:'Failed',status:'failed',detail:error.stack});process.exitCode=1;}).finally(async()=>{if(app)await app.close();await fs.writeFile(path.join(dir,'results.json'),JSON.stringify({results},null,2));console.log('Evidence:',dir);});
